"""nftables ruleset builder for the rogue segment.

services.py has always driven iptables. On modern distros that defaults to
the nft-backed userspace tool (same CLI), but on minimal imager/container
builds there is NO iptables binary at all — only `nft` — and the redirect +
isolation layer then silently no-ops. This module renders the exact equivalent
ruleset as an nft formula file (`nft -f`) and is kept a PURE function so the
generated policy is unit-testable without root or a live netns.

Two tables are emitted:

  * `ip malstrom`   — the v4 policy: whitelist bypass + redirect DNATs, the
    postrouting masquerade, and the FORWARD accepts / isolation drops.
  * `ip6 malstrom6` — the IPv6 policy: the rogue mesh serves no v6 (the portal
    hands out only dhcp v4 and never sends RAs), so v6 routed *through* the
    AP interface in either direction is dropped outright. This closes the
    "no IPv6 firewall at all" gap: a victim with autoconfigured global v6
    could otherwise reach the operator LAN via the box's v6 uplink while the
    v4 side was busy DNATing everything.

DNAT statements need a `nat`-family hook chain (a regular "marker" chain can
host them in iptables but not nft), so the redirect rules live directly in
the prerouting hook chain with `iifname` + daddr guards. Whitelisted clients
are prepended so their verdicts win: dns -> the public resolver, everything
else `accept` (skip the redirect DNATs).
"""

import re

TABLE_V4 = 'malstrom'
TABLE_V6 = 'malstrom6'


def _sanitize_iface(iface):
    if not iface or not re.fullmatch(r'[A-Za-z0-9_.:-]+', str(iface)):
        raise ValueError('bad interface name: %r' % (iface,))
    return str(iface)


def _sanitize_ip(value, what='address'):
    if not value or not re.fullmatch(r'[0-9.]+', str(value)):
        raise ValueError('bad ipv4 %s: %r' % (what, value))
    return str(value)


def _sanitize_cidr(value):
    if not value or not re.fullmatch(r'[0-9./]+', str(value)):
        raise ValueError('bad ipv4 cidr: %r' % (value,))
    return str(value)


def nft_ruleset(iface, portal_ip, portal_port, tls_port, dns_port,
                portal_net, resolver_ip, whitelist=(),
                sibling_nets=(), isolation=True):
    """Render the full nft -f ruleset."""
    iface = _sanitize_iface(iface)
    portal_ip = _sanitize_ip(portal_ip)
    portal_net = _sanitize_cidr(portal_net)
    resv = _sanitize_ip(resolver_ip, 'resolver')
    ports = []
    for p in (portal_port, tls_port, dns_port):
        try:
            p = int(p)
        except (TypeError, ValueError):
            raise ValueError('bad port: %r' % (p,))
        if not 1 <= p <= 65535:
            raise ValueError('port out of range: %d' % p)
        ports.append(p)
    portal_port, tls_port, dns_port = ports

    lines = [
        '# generated by malstrom (nft -f) — do not edit',
        'table ip %s {' % TABLE_V4,
        '\tchain prerouting {',
        '\t\ttype nat hook prerouting priority -100; policy accept;',
    ]

    # Whitelisted clients first: their DNS may pin to the public resolver and
    # everything else must skip the redirect DNATs outright.
    for ip in sorted(set(whitelist or ())):
        ip = _sanitize_ip(ip)
        lines.append('\t\tiifname "%s" ip saddr %s udp dport 53 dnat to %s:53'
                     % (iface, ip, resv))
        lines.append('\t\tiifname "%s" ip saddr %s tcp dport 53 dnat to %s:53'
                     % (iface, ip, resv))
        lines.append('\t\tiifname "%s" ip saddr %s accept' % (iface, ip))

    lines.append('\t\tiifname "%s" tcp dport 80 ip daddr != %s dnat to %s:%d'
                 % (iface, portal_ip, portal_ip, portal_port))
    lines.append('\t\tiifname "%s" tcp dport 443 ip daddr != %s dnat to %s:%d'
                 % (iface, portal_ip, portal_ip, tls_port))
    lines.append('\t\tiifname "%s" tcp dport 80 ip daddr %s dnat to %s:%d'
                 % (iface, portal_ip, portal_ip, portal_port))
    lines.append('\t\tiifname "%s" tcp dport 443 ip daddr %s dnat to %s:%d'
                 % (iface, portal_ip, portal_ip, tls_port))
    for proto in ('udp', 'tcp'):
        lines.append('\t\tiifname "%s" %s dport 53 ip daddr != %s dnat to %s:%d'
                     % (iface, proto, portal_ip, portal_ip, dns_port))
        lines.append('\t\tiifname "%s" %s dport 53 ip daddr %s dnat to %s:%d'
                     % (iface, proto, portal_ip, portal_ip, dns_port))

    lines.append('\t}')
    lines.append('\tchain postrouting {')
    lines.append('\t\ttype nat hook postrouting priority 100; policy accept;')
    lines.append('\t\tip saddr %s ip daddr != %s masquerade'
                 % (portal_net, portal_net))
    lines.append('\t}')
    lines.append('\tchain forward {')
    lines.append('\t\ttype filter hook forward priority 0; policy accept;')
    if isolation:
        # Drops are evaluated before the accepts below, mirroring the
        # iptables `-I FORWARD 1` anchoring: victim cross-talk and victim ->
        # sibling LAN traffic is refused while browsable internet is not.
        lines.append('\t\tiifname "%s" oifname "%s" drop' % (iface, iface))
        for cidr in sorted(set(sibling_nets or ())):
            cidr = _sanitize_cidr(cidr)
            lines.append('\t\tip saddr %s ip daddr %s drop' % (portal_net, cidr))
    lines.append('\t\tiifname "%s" accept' % iface)
    lines.append('\t\toifname "%s" accept' % iface)
    lines.append('\t}')
    lines.append('}')
    lines.append('table ip6 %s {' % TABLE_V6)
    lines.append('\tchain forward {')
    lines.append('\t\ttype filter hook forward priority 0; policy accept;')
    lines.append('\t\tiifname "%s" drop' % iface)
    lines.append('\t\toifname "%s" drop' % iface)
    lines.append('\t}')
    lines.append('}')
    return '\n'.join(lines) + '\n'